/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ptamagotchi;

import Actividades.BatallaLegendaria;
import Actividades.Batallar;
import Actividades.Caminar;
import Actividades.Entrenar;
import Actividades.Nadar;
import Alimentos.Alga;
import Alimentos.BabiriBerry;
import Alimentos.FigyBerry;
import Alimentos.GrepaBerry;
import Alimentos.TangaBerry;
import Mascota.Mascota;
import Medicamentos.PocionMaxima;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JButton;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Emanuel
 */
public class Tamagotchi extends javax.swing.JFrame {
    public Mascota mascota;
    public Nadar nadar;
    public Entrenar entrenar;
    public Caminar caminar;
    public Batallar batalla;
    public BatallaLegendaria batallaLegen;
    public Alga alga;
    public BabiriBerry Babiri;
    public FigyBerry Figy;
    public GrepaBerry Grepa;
    public TangaBerry Tanga;
    public PocionMaxima PocionMax;

    /**
     * Creates new form Tamagotchi
     */
    public Tamagotchi() {
        initComponents();
        mascota = new Mascota();
        nadar = new Nadar();
        entrenar = new Entrenar();
        caminar = new Caminar();
        batalla = new Batallar();
        batallaLegen = new BatallaLegendaria();
        alga = new Alga();
        Babiri = new BabiriBerry();
        Figy = new FigyBerry();
        Grepa = new GrepaBerry();
        Tanga = new TangaBerry();
        PocionMax = new PocionMaxima();
    }
    
    public void actualizarEdad(){
        this.lblEdad3.setText("Edad: "+mascota.getEdad());
    }

    public void actualizarBarra(){
        this.barEnergia.setValue(mascota.getEnergia());
        this.barHambre.setValue(mascota.getHambre());
        this.barAburrimiento.setValue(mascota.getAburrimiento());
        this.barNecesidades.setValue(mascota.getNecesidades());
    }
    
    public void actualizarEstadoSalud(boolean estado){
        if (estado) {
            this.lblEstadoSalud.setText("Estado: Saludable");
        } else {
            this.lblEstadoSalud.setText("Estado: Enfermo");
        }
    }
    
    public void ComprobarVida(){
        if (mascota.isVida()==false) {
            System.exit(0);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEdad2 = new javax.swing.JLabel();
        btnComenzar = new javax.swing.JButton();
        lblFondoInicio = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnAlga = new javax.swing.JButton();
        barAburrimiento = new javax.swing.JProgressBar();
        barEnergia = new javax.swing.JProgressBar();
        barHambre = new javax.swing.JProgressBar();
        barNecesidades = new javax.swing.JProgressBar();
        btnDescansar = new javax.swing.JButton();
        lblMascota = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblTextoImagen = new javax.swing.JLabel();
        lblEdad3 = new javax.swing.JLabel();
        lblMedicamentos = new javax.swing.JLabel();
        lblEstadoSalud = new javax.swing.JLabel();
        btnCaminar = new javax.swing.JButton();
        btnBabiri = new javax.swing.JButton();
        btnFigy = new javax.swing.JButton();
        btnGrepa = new javax.swing.JButton();
        btnTanga = new javax.swing.JButton();
        btnNadar = new javax.swing.JButton();
        btnEntrenar = new javax.swing.JButton();
        btnBatallar = new javax.swing.JButton();
        btnBatallaLegen = new javax.swing.JButton();
        btnSanitario = new javax.swing.JButton();
        btnCentroPo = new javax.swing.JButton();
        btnAventura = new javax.swing.JButton();
        btnPocionMax = new javax.swing.JButton();
        lblEscenario = new javax.swing.JLabel();

        lblEdad2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnComenzar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnComenzar.setForeground(new java.awt.Color(255, 255, 255));
        btnComenzar.setText("Comenzar");
        btnComenzar.setContentAreaFilled(false);
        btnComenzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComenzarActionPerformed(evt);
            }
        });
        getContentPane().add(btnComenzar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 150, 50));

        lblFondoInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo inicio.jpeg"))); // NOI18N
        getContentPane().add(lblFondoInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 400));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Hambre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 87, 60, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Energia:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 60, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Necesidades:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(533, 60, 90, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Aburrimiento:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 36, 100, -1));

        btnAlga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosComida/algaP1.png"))); // NOI18N
        btnAlga.setToolTipText("<html>FigyBerry:<br>\n        Energia: +5<br>\n        Hambre: -5<br>\n        Enfriamiento: 5 Segundos<html>");
        btnAlga.setContentAreaFilled(false);
        btnAlga.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosComida/algaP2.png"))); // NOI18N
        btnAlga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlgaActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlga, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 280, -1, -1));

        barAburrimiento.setToolTipText("");
        barAburrimiento.setStringPainted(true);
        getContentPane().add(barAburrimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 35, 175, 20));

        barEnergia.setStringPainted(true);
        getContentPane().add(barEnergia, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 175, 20));

        barHambre.setStringPainted(true);
        getContentPane().add(barHambre, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 85, 175, 20));

        barNecesidades.setStringPainted(true);
        getContentPane().add(barNecesidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 60, 175, 20));

        btnDescansar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/descansarP1.jpg"))); // NOI18N
        btnDescansar.setToolTipText("<html>Dormir:\n<br>" +
            "        Energia:	     +10\n<br>" +
            "        Hambre: 	     +5\n<br>" +
            "        Aburrimiento:  +5\n<br>" +
            "        Necesidades:    +5\n<br>" +
            "        Enfriamiento:  10 Segundos<html>");
        btnDescansar.setContentAreaFilled(false);
        btnDescansar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/descansarP2.jpg"))); // NOI18N
        btnDescansar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescansarActionPerformed(evt);
            }
        });
        getContentPane().add(btnDescansar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, -1, -1));

        lblMascota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagMascota/egg.png"))); // NOI18N
        getContentPane().add(lblMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 269, 270));

        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 126, 30));

        lblTextoImagen.setForeground(new java.awt.Color(255, 255, 255));
        lblTextoImagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lblTextoImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 120, 126, 30));

        lblEdad3.setForeground(new java.awt.Color(255, 255, 255));
        lblEdad3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lblEdad3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 48, 126, 30));

        lblMedicamentos.setForeground(new java.awt.Color(255, 255, 255));
        lblMedicamentos.setText("Medicamentos");
        lblMedicamentos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lblMedicamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 126, 30));

        lblEstadoSalud.setForeground(new java.awt.Color(255, 255, 255));
        lblEstadoSalud.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lblEstadoSalud, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 90, 126, 30));

        btnCaminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosActividades/caminarP1.png"))); // NOI18N
        btnCaminar.setToolTipText("<html>Caminar:<br>\n        Energia: -5<br>\n        Aburrimiento: -5<br>\n        Enfriamiento: 5 Segundos<html>");
        btnCaminar.setContentAreaFilled(false);
        btnCaminar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosActividades/caminarP2.png"))); // NOI18N
        btnCaminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCaminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 160, -1, -1));

        btnBabiri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosComida/BabiriBerryP1.png"))); // NOI18N
        btnBabiri.setToolTipText("<html>BabiriBerry:<br>\n        Energia: +15<br>\n        Hambre: -15<br>\n        Enfriamiento: 15 Segundos<html>");
        btnBabiri.setContentAreaFilled(false);
        btnBabiri.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosComida/BabiriBerryP2.png"))); // NOI18N
        btnBabiri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBabiriActionPerformed(evt);
            }
        });
        getContentPane().add(btnBabiri, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 240, -1, -1));

        btnFigy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosComida/FigyBerryP1.png"))); // NOI18N
        btnFigy.setToolTipText("<html>FigyBerry:<br>\n        Energia: +20<br>\n        Hambre: -20<br>\n        Enfriamiento: 20 Segundos<html>");
        btnFigy.setContentAreaFilled(false);
        btnFigy.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosComida/FigyBerryP2.png"))); // NOI18N
        btnFigy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFigyActionPerformed(evt);
            }
        });
        getContentPane().add(btnFigy, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 200, -1, -1));

        btnGrepa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosComida/GrepaBerryP1.png"))); // NOI18N
        btnGrepa.setToolTipText("<html>GrepaBerry:<br>\n        Energia: +10<br>\n        Hambre: -10<br>\n        Enfriamiento: 10 Segundos<html>");
        btnGrepa.setContentAreaFilled(false);
        btnGrepa.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosComida/GrepaBerryP2.png"))); // NOI18N
        btnGrepa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrepaActionPerformed(evt);
            }
        });
        getContentPane().add(btnGrepa, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 160, -1, -1));

        btnTanga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosComida/TangaBerryP1.png"))); // NOI18N
        btnTanga.setToolTipText("<html>TangaBerry:\n<br>" +
            "        Energia: +25\n<br>" +
            "        Hambre: -25\n<br>" +
            "        Enfriamiento: 25 Segundos<html>");
        btnTanga.setContentAreaFilled(false);
        btnTanga.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosComida/TangaBerryP2.png"))); // NOI18N
        btnTanga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTangaActionPerformed(evt);
            }
        });
        getContentPane().add(btnTanga, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 320, -1, -1));

        btnNadar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosActividades/nadarP1.png"))); // NOI18N
        btnNadar.setToolTipText("<html>Nadar:<br>\n        Energia: -10<br>\n        Aburrimiento: -10<br>\n        Enfriamiento: 10 Segundos<html>");
        btnNadar.setContentAreaFilled(false);
        btnNadar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosActividades/nadarP2.png"))); // NOI18N
        btnNadar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNadarActionPerformed(evt);
            }
        });
        getContentPane().add(btnNadar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 200, -1, -1));

        btnEntrenar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosActividades/entrenarP1.png"))); // NOI18N
        btnEntrenar.setToolTipText("<html>Entrenar:<br>\n        Energia: -15<br>\n        Aburrimiento: -15<br>\n        Enfriamiento: 15 Segundos<html>");
        btnEntrenar.setContentAreaFilled(false);
        btnEntrenar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosActividades/entrenarP2.png"))); // NOI18N
        btnEntrenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrenarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEntrenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 240, -1, -1));

        btnBatallar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosActividades/batallarP1.jpg"))); // NOI18N
        btnBatallar.setToolTipText("<html>Batallar:\n<br>" +
            "        Energia: -20\n<br>" +
            "        Aburrimiento: -20\n<br>" +
            "        Enfriamiento: 20 Segundos<html>");
        btnBatallar.setContentAreaFilled(false);
        btnBatallar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosActividades/batallarP2.jpg"))); // NOI18N
        btnBatallar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatallarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBatallar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 320, 45, 45));

        btnBatallaLegen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosActividades/batallalegendariaP1.jpg"))); // NOI18N
        btnBatallaLegen.setToolTipText("<html>Batalla Legendaria:\n<br>" +
            "        Energia: -25\n<br>" +
            "        Aburrimiento: -25\n<br>" +
            "        Enfriamiento: 25 Segundos<html>");
        btnBatallaLegen.setContentAreaFilled(false);
        btnBatallaLegen.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosActividades/batallalegendariaP2.jpg"))); // NOI18N
        btnBatallaLegen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatallaLegenActionPerformed(evt);
            }
        });
        getContentPane().add(btnBatallaLegen, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 280, 45, 45));

        btnSanitario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BañoP1.jpg"))); // NOI18N
        btnSanitario.setToolTipText("<html>Bañarse:\n<br>" +
            "        Necesidades: -10\n<br>" +
            "        Enfriamiento: 10 Segundos<html>");
        btnSanitario.setContentAreaFilled(false);
        btnSanitario.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BañoP2.jpg"))); // NOI18N
        btnSanitario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSanitarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnSanitario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, -1, -1));

        btnCentroPo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/centroPokeIconoP1.png"))); // NOI18N
        btnCentroPo.setToolTipText("\tIR AL CENTRO POKEMON");
        btnCentroPo.setContentAreaFilled(false);
        btnCentroPo.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/centroPokeIconoP2.png"))); // NOI18N
        btnCentroPo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCentroPoActionPerformed(evt);
            }
        });
        getContentPane().add(btnCentroPo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        btnAventura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/poke40.png"))); // NOI18N
        btnAventura.setToolTipText("\tIR DE EXPEDICION");
        btnAventura.setContentAreaFilled(false);
        btnAventura.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/poke50.png"))); // NOI18N
        btnAventura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAventuraActionPerformed(evt);
            }
        });
        getContentPane().add(btnAventura, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        btnPocionMax.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/maxpocionP1.png"))); // NOI18N
        btnPocionMax.setToolTipText("<html>PocionMaxima:<br>\n" +
            "        Energia:            -20\n<br>" +
            "        Hambre:           -20\n<br>" +
            "        Aburrimiento:  -20\n<br>" +
            "        Necesidades:    -20\n<br>" +
            "        Enfriamiento:    1 Dia.\n<br>" +
            " 	Condicionado:\n<br>" +
            "	Te cura si te encuentras enfermo y te aumenta\n<br>" +
            " 	la estadistica en CRITICO con los valores antes\n<br>" +
            "	dichos, pero ten cuidado sino \n<br>" +
            "	tienes ninguna estadistica en CRITICO, y te \n<br>" +
            "	encuentras saludable. Esta te hara enfermar.<html>");
        btnPocionMax.setContentAreaFilled(false);
        btnPocionMax.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/maxpocionP2.png"))); // NOI18N
        btnPocionMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPocionMaxActionPerformed(evt);
            }
        });
        getContentPane().add(btnPocionMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        lblEscenario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Aventura.jpg"))); // NOI18N
        getContentPane().add(lblEscenario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlgaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlgaActionPerformed
        // TODO add your handling code here:
        mascota.alimentar(alga);
        ComprobarVida();
        actualizarEstadoSalud(mascota.isEstadoSalud());
        this.btnAlga.setEnabled(false);
        temporizadorBotones(alga.getTiempoRestante(),this.btnAlga);
    }//GEN-LAST:event_btnAlgaActionPerformed

    private void btnComenzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComenzarActionPerformed
        // TODO add your handling code here:
        this.lblNombre.setText("Nombre: "+mascota.nombrarMascota());
        this.lblTextoImagen.setText("Actividades");
        actualizarEstadoSalud(mascota.isEstadoSalud());
        actualizarEdad();
        temporizadorEdad(15);
        actualizarBarra();
        temporizadorJuego();
        BotonesAlimentos(false);
        this.lblFondoInicio.setVisible(false);
        this.btnComenzar.setVisible(false);
        this.btnAventura.setVisible(false);
    }//GEN-LAST:event_btnComenzarActionPerformed

    public void BotonesAlimentos(boolean estado){
        this.btnAlga.setVisible(estado);
        this.btnGrepa.setVisible(estado);
        this.btnBabiri.setVisible(estado);
        this.btnFigy.setVisible(estado);
        this.btnTanga.setVisible(estado);

    }
    
    public void BotonesActividades(boolean estado){
        this.btnEntrenar.setVisible(estado);
        this.btnNadar.setVisible(estado);
        this.btnCaminar.setVisible(estado);
        this.btnBatallaLegen.setVisible(estado);
        this.btnBatallar.setVisible(estado);
    }
    
    private void btnBabiriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBabiriActionPerformed
        // TODO add your handling code here:
        mascota.alimentar(Babiri);
        ComprobarVida();
        actualizarEstadoSalud(mascota.isEstadoSalud());
        this.btnBabiri.setEnabled(false);
        temporizadorBotones(alga.getTiempoRestante(),this.btnBabiri);
    }//GEN-LAST:event_btnBabiriActionPerformed

    private void btnFigyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFigyActionPerformed
        // TODO add your handling code here:
        mascota.alimentar(Figy);
        ComprobarVida();
        actualizarEstadoSalud(mascota.isEstadoSalud());
        this.btnFigy.setEnabled(false);
        temporizadorBotones(Figy.getTiempoRestante(),this.btnFigy);
    }//GEN-LAST:event_btnFigyActionPerformed

    private void btnGrepaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrepaActionPerformed
        // TODO add your handling code here:
        mascota.alimentar(Grepa);
        ComprobarVida();
        actualizarEstadoSalud(mascota.isEstadoSalud());
        this.btnGrepa.setEnabled(false);
        temporizadorBotones(Grepa.getTiempoRestante(),this.btnGrepa);
    }//GEN-LAST:event_btnGrepaActionPerformed

    private void btnTangaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTangaActionPerformed
        // TODO add your handling code here:
        mascota.alimentar(Tanga);
        ComprobarVida();
        actualizarEstadoSalud(mascota.isEstadoSalud());
        this.btnTanga.setEnabled(false);
        temporizadorBotones(Tanga.getTiempoRestante(),this.btnTanga);
    }//GEN-LAST:event_btnTangaActionPerformed

    private void btnBatallaLegenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatallaLegenActionPerformed
        // TODO add your handling code here:
//        comprobarDobleEnfermedad();
        mascota.Actividad(this.batallaLegen);
        ComprobarVida();
        this.btnBatallaLegen.setEnabled(false);
        temporizadorBotones(batallaLegen.getTiempoRestante(),this.btnBatallaLegen);
    }//GEN-LAST:event_btnBatallaLegenActionPerformed

    private void btnCentroPoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCentroPoActionPerformed
        // TODO add your handling code here:
        this.btnCentroPo.setVisible(false);
        this.btnAventura.setVisible(true);
        this.lblEscenario.setIcon(new ImageIcon(getClass().getResource("/Imagenes/"+"centropokemonfondo.jpg")));
        this.lblTextoImagen.setText("Alimentos");
        BotonesAlimentos(true);
        BotonesActividades(false);
    }//GEN-LAST:event_btnCentroPoActionPerformed

    private void btnAventuraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAventuraActionPerformed
        // TODO add your handling code here:
        this.btnCentroPo.setVisible(true);
        this.btnAventura.setVisible(false);
        this.lblEscenario.setIcon(new ImageIcon(getClass().getResource("/Imagenes/"+"Aventura.jpg")));
        this.lblTextoImagen.setText("Actividades");
        BotonesAlimentos(false);
        BotonesActividades(true);
    }//GEN-LAST:event_btnAventuraActionPerformed

    private void btnCaminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaminarActionPerformed
        // TODO add your handling code here:
//        comprobarDobleEnfermedad();
        mascota.Actividad(caminar);
        ComprobarVida();
        actualizarEstadoSalud(mascota.isEstadoSalud());
        this.btnCaminar.setEnabled(false);
        temporizadorBotones(caminar.getTiempoRestante(),this.btnCaminar);
    }//GEN-LAST:event_btnCaminarActionPerformed

    private void btnNadarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNadarActionPerformed
        // TODO add your handling code here:
//        comprobarDobleEnfermedad();
        mascota.Actividad(nadar);
        ComprobarVida();
        actualizarEstadoSalud(mascota.isEstadoSalud());
        this.btnNadar.setEnabled(false);
        temporizadorBotones(nadar.getTiempoRestante(),this.btnNadar);
    }//GEN-LAST:event_btnNadarActionPerformed

    private void btnEntrenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrenarActionPerformed
        // TODO add your handling code here:
//        comprobarDobleEnfermedad();
        mascota.Actividad(entrenar);
        ComprobarVida();
        actualizarEstadoSalud(mascota.isEstadoSalud());
        this.btnEntrenar.setEnabled(false);
        temporizadorBotones(entrenar.getTiempoRestante(),this.btnEntrenar);
    }//GEN-LAST:event_btnEntrenarActionPerformed

    private void btnBatallarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatallarActionPerformed
        // TODO add your handling code here:
//        comprobarDobleEnfermedad();
        mascota.Actividad(batalla);
        ComprobarVida();
        actualizarEstadoSalud(mascota.isEstadoSalud());
        this.btnBatallar.setEnabled(false);
        temporizadorBotones(batalla.getTiempoRestante(),this.btnBatallar);
    }//GEN-LAST:event_btnBatallarActionPerformed

    private void btnDescansarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescansarActionPerformed
        // TODO add your handling code here:
//        comprobarDobleEnfermedad();
        mascota.Descansar();
        ComprobarVida();
        actualizarEstadoSalud(mascota.isEstadoSalud());
        this.btnDescansar.setEnabled(false);
        temporizadorBotones(10,this.btnDescansar);
    }//GEN-LAST:event_btnDescansarActionPerformed

    
    private void btnSanitarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSanitarioActionPerformed
        // TODO add your handling code here:
        mascota.IrAlSanitario();
        ComprobarVida();
        actualizarEstadoSalud(mascota.isEstadoSalud());
        this.btnSanitario.setEnabled(false);
        temporizadorBotones(10,this.btnSanitario);
    }//GEN-LAST:event_btnSanitarioActionPerformed

    private void btnPocionMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPocionMaxActionPerformed
        // TODO add your handling code here:
        mascota.usarMedicamento(PocionMax);
        ComprobarVida();
        actualizarEstadoSalud(mascota.isEstadoSalud());
        this.btnPocionMax.setEnabled(false);
        temporizadorBotones(PocionMax.getTiempoRestante(),this.btnPocionMax);
    }//GEN-LAST:event_btnPocionMaxActionPerformed

    public void temporizadorBotones(int retraso, JButton boton) {
        actualizarBarra();
        Timer timer = new Timer();
        timer.schedule(new TimerTask() {
            @Override
            public void run() {
                boton.setEnabled(true);
                timer.cancel();
            }
         ;},retraso * 1000);
    }
      
    
    public void temporizadorJuego() {
        Timer timer = new Timer();
        timer.schedule(new TimerTask() {
            @Override
            public void run() {
                mascota.avanceTiempo();
                actualizarEstadoSalud(mascota.isEstadoSalud());
                ComprobarVida();
                actualizarBarra();
                temporizadorJuego();
            }
         ;},5 * 1000);
    }
    
    public void temporizadorEdad(int tiempo) {
        Timer timer = new Timer();
        timer.schedule(new TimerTask() {
            @Override
            public void run() {
                actualizarEdad();
                if (mascota.isVida()==false) {
                    timer.cancel();
                }
                if (mascota.getEdad()==1) {
                    lblMascota.setIcon(new ImageIcon(getClass().getResource("/ImagMascota/"+"squirtle.gif")));
                } else if (mascota.getEdad()==10) {
                    lblMascota.setIcon(new ImageIcon(getClass().getResource("/ImagMascota/"+"wartortle.gif")));
                } else if (mascota.getEdad()==20) {
                    lblMascota.setIcon(new ImageIcon(getClass().getResource("/ImagMascota/"+"blastoise.gif")));
                }
                temporizadorEdad(tiempo);
            }
         ;},tiempo * 1000);
        mascota.incrementarEdad();
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tamagotchi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tamagotchi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tamagotchi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tamagotchi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tamagotchi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JProgressBar barAburrimiento;
    public javax.swing.JProgressBar barEnergia;
    public javax.swing.JProgressBar barHambre;
    public javax.swing.JProgressBar barNecesidades;
    private javax.swing.JButton btnAlga;
    private javax.swing.JButton btnAventura;
    private javax.swing.JButton btnBabiri;
    private javax.swing.JButton btnBatallaLegen;
    private javax.swing.JButton btnBatallar;
    private javax.swing.JButton btnCaminar;
    private javax.swing.JButton btnCentroPo;
    private javax.swing.JButton btnComenzar;
    private javax.swing.JButton btnDescansar;
    private javax.swing.JButton btnEntrenar;
    private javax.swing.JButton btnFigy;
    private javax.swing.JButton btnGrepa;
    private javax.swing.JButton btnNadar;
    private javax.swing.JButton btnPocionMax;
    private javax.swing.JButton btnSanitario;
    private javax.swing.JButton btnTanga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JLabel lblEdad2;
    public javax.swing.JLabel lblEdad3;
    private javax.swing.JLabel lblEscenario;
    public javax.swing.JLabel lblEstadoSalud;
    private javax.swing.JLabel lblFondoInicio;
    private javax.swing.JLabel lblMascota;
    public javax.swing.JLabel lblMedicamentos;
    public javax.swing.JLabel lblNombre;
    public javax.swing.JLabel lblTextoImagen;
    // End of variables declaration//GEN-END:variables
}
